@startuml
APP -> WM2: command
WM2 --> APP:response
== WM2註冊完成 ==
WM2 -> SSM: 1111
APP -> AWS: subscribe to topic, {shadowName: deviceUUID}
note right of AWS: $aws/things/wm2/shadow/\nname/\(shadowName)/update/accepted

AWS --> WM2: 影子狀態更新
WM2 --> APP: 更新設備狀態


@enduml