excluded:
- SesameSDKTests
- SesameSDK/KeychainSwiftDistrib.swift

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  warning: 250
  error: 1024

vertical_whitespace:
  max_empty_lines: 3

disabled_rules:
  - type_name
  - identifier_name